### ISSUE TITLE
AAI extraction problems

### ISSUE THREAD

**Issue by NikoofDeath** [Missingmew/phoenixtools#2] opened 2020-08-04 01:17 UTC
I'm trying to use your tools to extract AAI's files (specifically, I'm trying to get the main character sprites), but have run into two issues.
First of all, extract-edgeworth-romfile expects a filelist, but as far as I know none is available. I assume gk ids.xlsx is your progress in creating one, is the program not functional until that is available? 
Secondly (and this might be dependent on the answer to the first), after extracting simply using the romfile.bin as the filelist (for lack of a better option), I tried using convert-edgeworth-raw to convert the extracted files to PNG, using rows as tilesx, cols as tilesy, and the palette ID as the palette number. For 4bpp files, I get "selected a higher than possible palette!", and for 8bpp files (using 1 and 1 for tilesx and tilesy) I get "only 4bpp support multipalette!". Is there anything I'm doing wrong or are the tools simply incomplete?

**Comment by Missingmew** [comment] 2020-08-06 01:58
For `extract-edgeworth-romfile`, the filelist should technically be an optional argument (I have changes that fix this and a handful of other things done locally but never committed them so its on me). For the current version you can just pass an empty file as list. The expected format of the list is one line per file (with empty lines causing the default name to be used), if the end of the list is reached before all files have been dealt with it will keep using the default name.

As for `convert-edgeworth-raw`, the palette number is zero-based (so the first palette will be palette 0, the second will be palette 1) which is also the cause of the error message regarding multipalette for 8bpp (as that expects palette 0 as argument). You will also have to find the correct width and height in tiles for the file (so your test with 1 for each will fail unless the file is just 1 tile in size total). For some quick testing, you should be able to calculate the total number of tiles by taking the file size and dividing it by 64 for 8bpp and 32 for 4bpp, then use 1 for tilesx and the result for tilesy, adjusting each until it looks right. This will only work for images which do not rely on tilemaps and such (for which you would need the appropriate data which I have not yet tried finding)

As you can probably guess from the sheer number of arguments you need to pass to `edgeworth-raw`, the tool basically evolved from my findings and I just tacked on things as I went, a prime example of the "consider everything in here unstable and evil" phrase in the readme. I also havent put too much work into the edgeworth tools so they are most likely incomplete as well.

Edgeworth will probably stay on the back-burner for some time while I work on phoenix related things (as so far, phoenix and edgeworth share very little, if any, regarding their makeup)

**Closed** 2020-11-12 12:17 UTC
